# Install a specified list of sets and packages.
---
- name: Check if glibc has already been (re)installed with the user-defined-trusted-dirs option
  command: "strings {{ gentoo_prefix_path }}/usr/lib64/libc.a"
  register: glibc_reinstalled
  when: eessi_host_os == "linux"

- name: Reinstall glibc with the user-defined-trusted-dirs option
  portage:
    package: sys-libs/glibc
    noreplace: no
    oneshot: yes
  environment:
    EXTRA_EMAKE: "user-defined-trusted-dirs={{ prefix_user_defined_trusted_dir }}"
  when: eessi_host_os == "linux" and glibc_reinstalled.stdout | regex_search("^" + prefix_user_defined_trusted_dir + "/?$")

- name: Install package set {{ package_sets }}
  portage:
    package: "@{{ item }}"
    state: present
  with_items: "{{ package_sets }}"
  tags:
    - set

- name: Install additional packages
  portage:
    package: "{{ item }}"
    state: present
  with_items: "{{ prefix_packages }}"

- name: "Get the username running the deployment (not root)"
  command: whoami
  changed_when: false
  register: username_on_host
  tags:
    - fix_permissions
    - never

- name: "Fix permissions after installing as portage/root"
  file:
    owner: "{{ username_on_host.stdout }}"
    group: "{{ username_on_host.stdout }}"
    path: "{{ gentoo_prefix_path }}"
    recurse: true
  become: yes
  tags:
    - fix_permissions
    - never
